#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/di0ik/helm-charts/tree/main/helm/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/di0ik/wireguard
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  # @default -- chart.appVersion
  tag:


# -- Configure configMaps for the chart here.
# Additional configMaps can be added by adding a dictionary key similar to the 'config' object.
# @default -- See values.yaml
wireguard:
  config:
    # -- WireGuard manual configuration
    # -- Enables or disables the configMap
    manualConfig: false
    # -- configMap data content.
    # @default -- See values.yaml
    configContent: |
      [Interface]
      Address = 10.200.200.1/24
      PostUp =   iptables -I FORWARD 1 -i wg0 -j ACCEPT; iptables -I FORWARD 1 -o wg0 -j ACCEPT; iptables -t nat -I POSTROUTING 1 -s 10.200.200.0/24 -o eth0 -j MASQUERADE
      PostDown = iptables -D FORWARD -i wg0 -j ACCEPT;   iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.200.200.0/24 -o eth0 -j MASQUERADE
      ListenPort = 51820
      PrivateKey = [Server's private key]

      [Peer]
      # friendly_name = Client 1
      PublicKey = [Client's public key]
      AllowedIPs = 10.200.200.2/32
      PresharedKey = [Pre-shared key, same for server and client]

      [Peer]
      # friendly_name = Client 2
      PublicKey = [Client's public key]
      AllowedIPs = 10.200.200.2/32
      PresharedKey = [Pre-shared key, same for server and client]
    
    # -- Automatically generate the configMap
    # @default -- See values.yaml
    autoConfig: true
    # -- WireGuard configuration
    # @default -- See values.yaml
    auto:
      interface:
        # -- WireGuard interface address
        address: 10.200.200.1/24
        masquerade: true
        port: 51820
        privateKey: [Server's private key]
      
      peers:
        client1:
          publicKey: [Client's public key]
          allowedIPs: 10.200.200.2/32
          presharedKey: [Pre-shared key, same for server and client]
